SELECT B.ACCOUNT LDAP_ID
  FROM ACCOUNT_TOKEN A INNER JOIN ACCOUNTS B ON A.ACCOUNT_UID = B.ACCOUNT_UID
 WHERE     A.ACCESS_TOKEN = $1::VARCHAR
       AND A.EXPIRATION_DATE >= DATE_TRUNC('day', now())
       AND A.IS_EFFECTIVE = 'Y'