SELECT ROWNUM ROW_NUM_ID,
       B.ACCOUNT,
       B.name,
       A.*
  FROM ACCOUNT_AVAILABLE_SYSTEMS A, ACCOUNTS B
 WHERE     A.ACCOUNT_UID = B.ACCOUNT_UID
       AND A.SYSTEM_UID = :administrator_SYSTEM_UID