UPDATE ACCOUNT_AVAILABLE_SYSTEMS
   SET EXPIRATION_DATE = TO_DATE ( :EXPIRATION_DATE, 'YYYY/MM/DD'),
       UP_DATE = SYSDATE,
       UP_USER =
          (SELECT C.ACCOUNT
             FROM ACCOUNT_TOKEN A, ACCOUNTS C
            WHERE     A.ACCESS_TOKEN = :ACCESS_TOKEN
                  AND a.EXPIRATION_DATE >= TRUNC (SYSDATE)
                  AND A.IS_EFFECTIVE = 'Y'
                  AND A.ACCOUNT_UID = C.ACCOUNT_UID)
 WHERE     (SELECT C.ACCOUNT
              FROM ACCOUNT_TOKEN A, ACCOUNTS C
             WHERE     A.ACCESS_TOKEN = :ACCESS_TOKEN
                   AND a.EXPIRATION_DATE >= TRUNC (SYSDATE)
                   AND A.IS_EFFECTIVE = 'Y'
                   AND A.ACCOUNT_UID = C.ACCOUNT_UID)
              IS NOT NULL
       AND SYSTEM_UID = :SYSTEM_UID
       AND ACCOUNT_UID = :ACCOUNT_UID