SELECT ROWNUM ROW_NUM_ID,
       A.GROUP_UID,
       B.ACCOUNT_UID,
       B.ACCOUNT,
       B.NAME
  FROM ACCOUNT_GROUPS A
       INNER JOIN ACCOUNTS B ON A.ACCOUNT_UID = B.ACCOUNT_UID
 WHERE     A.GROUP_UID = :GROUP_UID
       AND (   UPPER (B.ACCOUNT) LIKE '%' || UPPER ( :SEARCH_VALUE) || '%'
            OR UPPER (B.NAME) LIKE '%' || UPPER ( :SEARCH_VALUE) || '%')