SELECT B.ACCOUNT LDAP_ID
  FROM ACCOUNT_TOKEN A INNER JOIN ACCOUNTS B ON A.ACCOUNT_UID = B.ACCOUNT_UID
 WHERE     A.ACCESS_TOKEN = :ACCESS_TOKEN
       AND A.EXPIRATION_DATE >= TRUNC (SYSDATE)
       AND A.IS_EFFECTIVE = 'Y'