    SELECT ROWNUM ROW_NUM_ID,
           CASE
              WHEN :group_GROUP_NAME IS NULL THEN 'N'
              WHEN A.GROUP_NAME LIKE '%' || :group_GROUP_NAME || '%' THEN 'Y'
              ELSE 'N'
           END
              UNFOLD,
           A.GROUP_UID,
           A.GROUP_NAME,
           A.IS_CORE,
           A.ENABLED,
           A.PARENT_GROUP_UID,
           B.GROUP_NAME PARENT_GROUP_NAME,
           LEVEL
      FROM GROUP_LIST A
           LEFT JOIN GROUP_LIST B ON B.GROUP_UID = A.PARENT_GROUP_UID
START WITH A.PARENT_GROUP_UID IS NULL
CONNECT BY A.PARENT_GROUP_UID = PRIOR A.GROUP_UID
  ORDER BY LEVEL