MERGE INTO GROUP_LIST t
     USING (SELECT C.ACCOUNT, B.*
              FROM ACCOUNT_TOKEN A, GROUP_LIST B, ACCOUNTS C
             WHERE     A.ACCESS_TOKEN = :ACCESS_TOKEN
                   AND EXPIRATION_DATE >= TRUNC (SYSDATE)
                   AND IS_EFFECTIVE = 'Y'
                   AND B.GROUP_UID = :GROUP_UID
                   AND A.ACCOUNT_UID = C.ACCOUNT_UID) s
        ON (t.GROUP_UID = s.GROUP_UID)
WHEN MATCHED
THEN
   UPDATE SET GROUP_NAME = :GROUP_NAME,
              IS_CORE = :IS_CORE,
              ENABLED = :ENABLED,
              PARENT_GROUP_UID = :PARENT_GROUP_UID,
              UP_USER = S.ACCOUNT,
              UP_DATE = SYSDATE