SELECT ROWNUM ROW_NUM_ID,
   A.* FROM SYSTEM_PLATFORM A WHERE 
   (
   UPPER(PLATFORM_CODE) LIKE '%' || UPPER(:SEARCH_VALUE) || '%'
   OR
   UPPER(PLATFORM_NAME) LIKE '%' || UPPER(:SEARCH_VALUE) || '%'
   )  ORDER BY A.SEQ