  SELECT ROWNUM ROW_NUM_ID, A.*
    FROM FUNCTION_LIST A
   WHERE     PROGRAM_UID = NVL ( :functionadmin_PROGRAM_UID, PROGRAM_UID)
         AND SYSTEM_UID = NVL ( :functionadmin_SYSTEM_UID, SYSTEM_UID)
ORDER BY SEQ