INSERT INTO ACCOUNT_AVAILABLE_SYSTEMS 
(ACCOUNT_UID, SYSTEM_UID, UP_USER, CREATE_USER)
SELECT C.ACCOUNT_UID, :SYSTEM_UID, C.ACCOUNT, C.ACCOUNT
             FROM ACCOUNT_TOKEN A, ACCOUNTS C
            WHERE     A.ACCESS_TOKEN = :ACCESS_TOKEN
                  AND a.EXPIRATION_DATE >= TRUNC (SYSDATE)
                  AND A.IS_EFFECTIVE = 'Y'
                  AND A.ACCOUNT_UID = C.ACCOUNT_UID