  SELECT *
    FROM (SELECT 'WEB' SYSTEM_TYPE, 'WEB' SYSTEM_TYPE_NAME, 1 SEQ FROM DUAL
          UNION ALL
          SELECT 'APP' SYSTEM_TYPE, 'APP' SYSTEM_TYPE_NAME, 2 SEQ FROM DUAL
          UNION ALL
          SELECT 'ZK' SYSTEM_TYPE, 'ZK' SYSTEM_TYPE_NAME, 3 SEQ FROM DUAL)
ORDER BY SEQ