MERGE INTO SYSTEM_LIST t
     USING (SELECT C.ACCOUNT, B.SYSTEM_UID
              FROM ACCOUNT_TOKEN A, SYSTEM_LIST B, ACCOUNTS C
             WHERE     A.ACCESS_TOKEN = :ACCESS_TOKEN
                   AND EXPIRATION_DATE >= TRUNC (SYSDATE)
                   AND IS_EFFECTIVE = 'Y'
                   AND B.SYSTEM_UID = :SYSTEM_UID
                   AND A.ACCOUNT_UID = C.ACCOUNT_UID) s
        ON (t.SYSTEM_UID = s.SYSTEM_UID)
WHEN MATCHED
THEN
   UPDATE SET SYSTEM_NAME = :SYSTEM_NAME,
              SYSTEM_DESC = :SYSTEM_DESC,
              ENABLED = :ENABLED,
              SYSTEM_TYPE = :SYSTEM_TYPE,
              UP_DATE = SYSDATE,
              UP_USER = S.ACCOUNT