MERGE INTO PROGRAM_LIST t
     USING (SELECT C.ACCOUNT, B.*
              FROM ACCOUNT_TOKEN A, PROGRAM_LIST B, ACCOUNTS C
             WHERE     A.ACCESS_TOKEN = :ACCESS_TOKEN
                   AND EXPIRATION_DATE >= TRUNC (SYSDATE)
                   AND IS_EFFECTIVE = 'Y'
                   AND B.PROGRAM_UID = :PROGRAM_UID
                   AND A.ACCOUNT_UID = C.ACCOUNT_UID) s
        ON (t.PROGRAM_UID = s.PROGRAM_UID)
WHEN MATCHED
THEN
   UPDATE SET
      PROGRAM_CODE = NVL ( :PROGRAM_CODE, s.PROGRAM_CODE),
      PROGRAM_NAME = :PROGRAM_NAME,
      I18N = :I18N,
      ICON = :ICON,
      PATH = NVL ( :PATH, s.PATH),
      IS_DIR =
         CASE
            WHEN :IS_DIR IS NOT NULL THEN :IS_DIR
            WHEN NVL ( :PATH, s.PATH) IS NULL THEN 'Y'
            ELSE 'N'
         END,
      SEQ = :SEQ,
      ENABLED = :ENABLED,
      UP_USER = S.ACCOUNT,
      UP_DATE = SYSDATE